fos_user:
    db_driver: mongodb # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Cmn\UserBundle\Document\User
    group:
        group_class: Cmn\UserBundle\Document\Group
    service:
            user_manager: sonata.user.mongodb.user_manager